/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package monopoly.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import monopoly.functional.Player;
import monopoly.functional.Players;
import monopoly.functional.Util;
import monopoly.functional.squares.CommuinityChest;

/**
 *
 * @author ivan
 */
public class Board extends javax.swing.JFrame {
    
    private JButton[] btnPlayersArray, btnEditsArray, btnTokensArray;
    private JTextField[] playerNamesArray;
//    private ArrayList<Integer> initialDice;
    private boolean gameStarted = false;
    private JButton currentPlayerToEdit;
    private int numOfPlayers;

    /**
     * Creates new form Tablero
     */
    public Board() {
        initComponents();
        initArrays();
        initButtonCommands();
        toggleComponents(0);
        numOfPlayers = numOfPlayers = Integer.parseInt(txfNumOfPlayers.getText());
        Util.getUtil().setBoard(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnP1 = new javax.swing.JButton();
        btnP2 = new javax.swing.JButton();
        btnP3 = new javax.swing.JButton();
        btnP4 = new javax.swing.JButton();
        btnP5 = new javax.swing.JButton();
        btnP6 = new javax.swing.JButton();
        CommunityChestButton = new javax.swing.JButton();
        ChanceButton = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        pnlStartGameOptions = new javax.swing.JPanel();
        lblAmmountOfPlayers = new javax.swing.JLabel();
        btnDice = new javax.swing.JButton();
        txfNumOfPlayers = new javax.swing.JTextField();
        btnMinusNumOfPlayers = new javax.swing.JButton();
        btnPlusNumOfPlayers = new javax.swing.JButton();
        btnSelectNumOfPlayers = new javax.swing.JButton();
        txfPlayerTurn = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        btnToken1 = new javax.swing.JButton();
        btnToken2 = new javax.swing.JButton();
        btnToken3 = new javax.swing.JButton();
        btnToken4 = new javax.swing.JButton();
        btnToken5 = new javax.swing.JButton();
        btnToken6 = new javax.swing.JButton();
        btnToken7 = new javax.swing.JButton();
        btnToken8 = new javax.swing.JButton();
        btnToken9 = new javax.swing.JButton();
        btnToken10 = new javax.swing.JButton();
        btnToken11 = new javax.swing.JButton();
        btnToken12 = new javax.swing.JButton();
        btnToken13 = new javax.swing.JButton();
        btnToken14 = new javax.swing.JButton();
        txfEditPlayer1 = new javax.swing.JTextField();
        lblTurn = new javax.swing.JLabel();
        btnEditPlayer1 = new javax.swing.JButton();
        btnEditPlayer2 = new javax.swing.JButton();
        txfEditPlayer2 = new javax.swing.JTextField();
        txfEditPlayer3 = new javax.swing.JTextField();
        btnEditPlayer3 = new javax.swing.JButton();
        btnEditPlayer4 = new javax.swing.JButton();
        txfEditPlayer4 = new javax.swing.JTextField();
        btnEditPlayer5 = new javax.swing.JButton();
        btnEditPlayer6 = new javax.swing.JButton();
        txfEditPlayer5 = new javax.swing.JTextField();
        txfEditPlayer6 = new javax.swing.JTextField();
        txfDiceResult = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 227, 199));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnP1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnP1.setOpaque(false);
        btnP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 860, 50, 50));

        btnP2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnP2.setOpaque(false);
        btnP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 860, 50, 50));

        btnP3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnP3.setOpaque(false);
        btnP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 860, 50, 50));

        btnP4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnP4.setOpaque(false);
        btnP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 860, 50, 50));

        btnP5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnP5.setOpaque(false);
        btnP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 860, 50, 50));

        btnP6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnP6.setOpaque(false);
        btnP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnP6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 860, 50, 50));

        CommunityChestButton.setBorder(null);
        CommunityChestButton.setBorderPainted(false);
        CommunityChestButton.setOpaque(false);
        CommunityChestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityChestButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CommunityChestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 185, 160, 150));

        ChanceButton.setBorder(null);
        ChanceButton.setBorderPainted(false);
        ChanceButton.setOpaque(false);
        ChanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChanceButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ChanceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 630, 130, 130));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boardEdit.png"))); // NOI18N
        lblBackground.setText("jLabel2");
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 960, -1));

        pnlStartGameOptions.setBackground(new java.awt.Color(204, 227, 199));
        pnlStartGameOptions.setFocusable(false);
        pnlStartGameOptions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAmmountOfPlayers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAmmountOfPlayers.setForeground(new java.awt.Color(0, 0, 0));
        lblAmmountOfPlayers.setText("Cantidad de jugadores:");
        pnlStartGameOptions.add(lblAmmountOfPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, -1, -1));

        btnDice.setText("Dados");
        btnDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiceActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(btnDice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txfNumOfPlayers.setEditable(false);
        txfNumOfPlayers.setBackground(new java.awt.Color(255, 255, 255));
        txfNumOfPlayers.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txfNumOfPlayers.setForeground(new java.awt.Color(0, 0, 0));
        txfNumOfPlayers.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNumOfPlayers.setText("2");
        txfNumOfPlayers.setFocusable(false);
        txfNumOfPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNumOfPlayersActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(txfNumOfPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 100, -1));

        btnMinusNumOfPlayers.setText("-");
        btnMinusNumOfPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusNumOfPlayersActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(btnMinusNumOfPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 100, -1));

        btnPlusNumOfPlayers.setText("+");
        btnPlusNumOfPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusNumOfPlayersActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(btnPlusNumOfPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 100, -1));

        btnSelectNumOfPlayers.setText("Seleccionar");
        btnSelectNumOfPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectNumOfPlayersActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(btnSelectNumOfPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 100, -1));

        txfPlayerTurn.setEditable(false);
        txfPlayerTurn.setBackground(new java.awt.Color(204, 227, 199));
        txfPlayerTurn.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txfPlayerTurn.setForeground(new java.awt.Color(0, 0, 0));
        txfPlayerTurn.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txfPlayerTurn.setText("2");
        txfPlayerTurn.setBorder(null);
        txfPlayerTurn.setFocusable(false);
        txfPlayerTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPlayerTurnActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(txfPlayerTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 310, 20));

        btnStart.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnStart.setText("Iniciar");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(btnStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 320, 30));

        btnToken1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BuqueDeGuerra.png"))); // NOI18N
        btnToken1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnToken1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToken1ActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(btnToken1, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 82, 50, 50));

        btnToken2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Caretilla.png"))); // NOI18N
        btnToken2.setText("jButton1");
        btnToken2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStartGameOptions.add(btnToken2, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 82, 50, 50));

        btnToken3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Perro.png"))); // NOI18N
        btnToken3.setText("jButton1");
        btnToken3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStartGameOptions.add(btnToken3, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 82, 50, 50));

        btnToken4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Plancha.png"))); // NOI18N
        btnToken4.setText("jButton1");
        btnToken4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStartGameOptions.add(btnToken4, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 82, 50, 50));

        btnToken5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dedal.png"))); // NOI18N
        btnToken5.setText("jButton1");
        btnToken5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStartGameOptions.add(btnToken5, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 137, 50, 50));

        btnToken6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sombrero.png"))); // NOI18N
        btnToken6.setText("jButton1");
        btnToken6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStartGameOptions.add(btnToken6, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 137, 50, 50));

        btnToken7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vehiculo.png"))); // NOI18N
        btnToken7.setText("jButton1");
        btnToken7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStartGameOptions.add(btnToken7, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 137, 50, 50));

        btnToken8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zapato.png"))); // NOI18N
        btnToken8.setText("jButton1");
        btnToken8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStartGameOptions.add(btnToken8, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 137, 50, 50));

        btnToken9.setText("jButton1");
        btnToken9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStartGameOptions.add(btnToken9, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 192, 50, 50));

        btnToken10.setText("jButton1");
        btnToken10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStartGameOptions.add(btnToken10, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 192, 50, 50));

        btnToken11.setText("jButton1");
        btnToken11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStartGameOptions.add(btnToken11, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 192, 50, 50));

        btnToken12.setText("jButton1");
        btnToken12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStartGameOptions.add(btnToken12, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 192, 50, 50));

        btnToken13.setText("jButton1");
        btnToken13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStartGameOptions.add(btnToken13, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 247, 50, 50));

        btnToken14.setText("jButton1");
        btnToken14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlStartGameOptions.add(btnToken14, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 247, 50, 50));

        txfEditPlayer1.setBackground(new java.awt.Color(255, 255, 255));
        txfEditPlayer1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txfEditPlayer1.setForeground(new java.awt.Color(0, 0, 0));
        txfEditPlayer1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfEditPlayer1.setText("1");
        txfEditPlayer1.setMinimumSize(new java.awt.Dimension(100, 42));
        txfEditPlayer1.setPreferredSize(new java.awt.Dimension(230, 24));
        txfEditPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEditPlayer1ActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(txfEditPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, -1));

        lblTurn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTurn.setForeground(new java.awt.Color(0, 0, 0));
        lblTurn.setText("Turno de jugador:");
        lblTurn.setToolTipText("");
        pnlStartGameOptions.add(lblTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        btnEditPlayer1.setText("Editar");
        btnEditPlayer1.setFocusable(false);
        btnEditPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPlayer1ActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(btnEditPlayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        btnEditPlayer2.setText("Editar");
        btnEditPlayer2.setFocusable(false);
        btnEditPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPlayer2ActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(btnEditPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        txfEditPlayer2.setBackground(new java.awt.Color(255, 255, 255));
        txfEditPlayer2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txfEditPlayer2.setForeground(new java.awt.Color(0, 0, 0));
        txfEditPlayer2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfEditPlayer2.setText("2");
        txfEditPlayer2.setMinimumSize(new java.awt.Dimension(100, 42));
        txfEditPlayer2.setPreferredSize(new java.awt.Dimension(230, 24));
        txfEditPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEditPlayer2ActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(txfEditPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, -1));

        txfEditPlayer3.setBackground(new java.awt.Color(255, 255, 255));
        txfEditPlayer3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txfEditPlayer3.setForeground(new java.awt.Color(0, 0, 0));
        txfEditPlayer3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfEditPlayer3.setText("3");
        txfEditPlayer3.setMinimumSize(new java.awt.Dimension(100, 42));
        txfEditPlayer3.setPreferredSize(new java.awt.Dimension(230, 24));
        txfEditPlayer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEditPlayer3ActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(txfEditPlayer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 250, -1));

        btnEditPlayer3.setText("Editar");
        btnEditPlayer3.setFocusable(false);
        btnEditPlayer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPlayer3ActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(btnEditPlayer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        btnEditPlayer4.setText("Editar");
        btnEditPlayer4.setFocusable(false);
        btnEditPlayer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPlayer4ActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(btnEditPlayer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        txfEditPlayer4.setBackground(new java.awt.Color(255, 255, 255));
        txfEditPlayer4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txfEditPlayer4.setForeground(new java.awt.Color(0, 0, 0));
        txfEditPlayer4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfEditPlayer4.setText("4");
        txfEditPlayer4.setMinimumSize(new java.awt.Dimension(100, 42));
        txfEditPlayer4.setPreferredSize(new java.awt.Dimension(230, 24));
        txfEditPlayer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEditPlayer4ActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(txfEditPlayer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 250, -1));

        btnEditPlayer5.setText("Editar");
        btnEditPlayer5.setFocusable(false);
        btnEditPlayer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPlayer5ActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(btnEditPlayer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        btnEditPlayer6.setText("Editar");
        btnEditPlayer6.setFocusable(false);
        btnEditPlayer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPlayer6ActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(btnEditPlayer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        txfEditPlayer5.setBackground(new java.awt.Color(255, 255, 255));
        txfEditPlayer5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txfEditPlayer5.setForeground(new java.awt.Color(0, 0, 0));
        txfEditPlayer5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfEditPlayer5.setText("5");
        txfEditPlayer5.setMinimumSize(new java.awt.Dimension(100, 42));
        txfEditPlayer5.setPreferredSize(new java.awt.Dimension(230, 24));
        txfEditPlayer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEditPlayer5ActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(txfEditPlayer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, -1));

        txfEditPlayer6.setBackground(new java.awt.Color(255, 255, 255));
        txfEditPlayer6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txfEditPlayer6.setForeground(new java.awt.Color(0, 0, 0));
        txfEditPlayer6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfEditPlayer6.setText("6");
        txfEditPlayer6.setMinimumSize(new java.awt.Dimension(100, 42));
        txfEditPlayer6.setPreferredSize(new java.awt.Dimension(230, 24));
        txfEditPlayer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEditPlayer6ActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(txfEditPlayer6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 250, -1));

        txfDiceResult.setEditable(false);
        txfDiceResult.setBackground(new java.awt.Color(204, 227, 199));
        txfDiceResult.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txfDiceResult.setForeground(new java.awt.Color(0, 0, 0));
        txfDiceResult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfDiceResult.setText("2");
        txfDiceResult.setBorder(null);
        txfDiceResult.setFocusable(false);
        txfDiceResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDiceResultActionPerformed(evt);
            }
        });
        pnlStartGameOptions.add(txfDiceResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 24));

        jPanel1.add(pnlStartGameOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 560, 350));

        jPanel2.setBackground(new java.awt.Color(204, 227, 199));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 350, 560, 610));

        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 630, 130, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP1ActionPerformed
        showPlayerData(1);
    }//GEN-LAST:event_btnP1ActionPerformed

    private void txfEditPlayer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEditPlayer6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfEditPlayer6ActionPerformed

    private void txfEditPlayer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEditPlayer5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfEditPlayer5ActionPerformed

    private void txfEditPlayer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEditPlayer4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfEditPlayer4ActionPerformed

    private void btnEditPlayer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPlayer3ActionPerformed
        selectPlayerToEdit(3);
    }//GEN-LAST:event_btnEditPlayer3ActionPerformed

    private void txfEditPlayer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEditPlayer3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfEditPlayer3ActionPerformed

    private void txfEditPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEditPlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfEditPlayer2ActionPerformed

    private void txfEditPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEditPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfEditPlayer1ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        toggleComponents(4);
        startGame();
    }//GEN-LAST:event_btnStartActionPerformed

    private void txfPlayerTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPlayerTurnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPlayerTurnActionPerformed

    private void btnSelectNumOfPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectNumOfPlayersActionPerformed
        toggleComponents(1);
        JOptionPane.showMessageDialog(this, "Para comenzar el juego, todos deben tener una ficha para jugar, "
                + "para definir la ficha solo haga click en editar y escoja una de las opciones."
                + "Adicionalmente, puede modificar el nombre a gusto.","Inicio", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSelectNumOfPlayersActionPerformed

    private void btnPlusNumOfPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusNumOfPlayersActionPerformed
        numOfPlayers += 1;
        txfNumOfPlayers.setText(Integer.toString(numOfPlayers));
        if (numOfPlayers < 2 || numOfPlayers > 6)
        btnSelectNumOfPlayers.setVisible(false);
        else if (!btnSelectNumOfPlayers.isVisible())
        btnSelectNumOfPlayers.setVisible(true);
    }//GEN-LAST:event_btnPlusNumOfPlayersActionPerformed

    private void btnMinusNumOfPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusNumOfPlayersActionPerformed
        numOfPlayers -= 1;
        txfNumOfPlayers.setText(Integer.toString(numOfPlayers));
        if (numOfPlayers < 2 || numOfPlayers > 6)
        btnSelectNumOfPlayers.setVisible(false);
        else if (!btnSelectNumOfPlayers.isVisible())
        btnSelectNumOfPlayers.setVisible(true);
    }//GEN-LAST:event_btnMinusNumOfPlayersActionPerformed

    private void txfNumOfPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNumOfPlayersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNumOfPlayersActionPerformed

    private void btnDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiceActionPerformed
        int res = Util.getUtil().getRandom().nextInt(6) + Util.getUtil().getRandom().nextInt(6) + 2;
        Util.getUtil().getPlayers().movePlayer(res);
        txfPlayerTurn.setText(Integer.toString(res));
        txfPlayerTurn.setText(Util.getUtil().getPlayers().getPlayerTurnName());
    }//GEN-LAST:event_btnDiceActionPerformed

    private void btnEditPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPlayer1ActionPerformed
        selectPlayerToEdit(1);
    }//GEN-LAST:event_btnEditPlayer1ActionPerformed

    private void btnEditPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPlayer2ActionPerformed
        selectPlayerToEdit(2);
    }//GEN-LAST:event_btnEditPlayer2ActionPerformed

    private void btnEditPlayer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPlayer4ActionPerformed
        selectPlayerToEdit(4);
    }//GEN-LAST:event_btnEditPlayer4ActionPerformed

    private void btnEditPlayer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPlayer5ActionPerformed
        selectPlayerToEdit(5);
    }//GEN-LAST:event_btnEditPlayer5ActionPerformed

    private void btnEditPlayer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPlayer6ActionPerformed
        selectPlayerToEdit(6);
    }//GEN-LAST:event_btnEditPlayer6ActionPerformed

    private void btnToken1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToken1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnToken1ActionPerformed

    private void txfDiceResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDiceResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDiceResultActionPerformed

    private void btnP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP2ActionPerformed
        showPlayerData(2);
    }//GEN-LAST:event_btnP2ActionPerformed

    private void btnP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP3ActionPerformed
        showPlayerData(3);
    }//GEN-LAST:event_btnP3ActionPerformed

    private void btnP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP4ActionPerformed
        showPlayerData(4);
    }//GEN-LAST:event_btnP4ActionPerformed

    private void btnP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP5ActionPerformed
        showPlayerData(5);
    }//GEN-LAST:event_btnP5ActionPerformed

    private void btnP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnP6ActionPerformed
        showPlayerData(6);
    }//GEN-LAST:event_btnP6ActionPerformed

    private void ChanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChanceButtonActionPerformed
         CommunnityChestMassage();
    }//GEN-LAST:event_ChanceButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CommunityChestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityChestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommunityChestButtonActionPerformed

    private void startGame() {
        JButton[] buttons = new JButton[numOfPlayers];
        String[] playerNames = new String[numOfPlayers];
        for (int i = 0; i < numOfPlayers; i++) {
            buttons[i] = btnPlayersArray[i];
            playerNames[i] = playerNamesArray[i].getText();
        }
        Util.getUtil().getPlayers().initPlayers(numOfPlayers, buttons, playerNames);
        gameStarted = true;
    }
    
    private void initArrays() {
        btnPlayersArray = new JButton[] {btnP1, btnP2, btnP3, btnP4, btnP5, btnP6};
        playerNamesArray = new JTextField[] {txfEditPlayer1, txfEditPlayer2, txfEditPlayer3,
            txfEditPlayer4, txfEditPlayer5, txfEditPlayer6};
        btnEditsArray = new JButton[] {btnEditPlayer1, btnEditPlayer2, btnEditPlayer3,
            btnEditPlayer4, btnEditPlayer5, btnEditPlayer6};
        btnTokensArray = new JButton[] {btnToken1, btnToken2, btnToken3, btnToken4,
            btnToken5, btnToken6, btnToken7, btnToken8, btnToken9, btnToken10, btnToken11,
            btnToken12, btnToken13, btnToken14};
    }
    
    private void initButtonCommands() {
        for (JButton jb : btnTokensArray) {
             jb.addActionListener((ActionEvent ae) -> {
                currentPlayerToEdit.setIcon(((JButton)ae.getSource()).getIcon());
                currentPlayerToEdit.setOpaque(false);
                toggleComponents(3);
                if (isGameReadyToStart())
                    btnStart.setVisible(true);
            });
        }
    }
    
    private boolean isGameReadyToStart() {
        for (int i = 0; i < numOfPlayers; i++)
            if (btnPlayersArray[i].getIcon() == null)
                return false;
        return true;
    }
    
    private void toggleComponents(int procedure) {
        switch (procedure) {
            case 0 -> {
                //initial toggles
                for (int i = 0; i < 6; i++) {
                    btnPlayersArray[i].setVisible(false);
                    playerNamesArray[i].setVisible(false);
                    btnEditsArray[i].setVisible(false);
                }   
                for (JButton jb : btnTokensArray)
                    jb.setVisible(false);
                btnDice.setVisible(false);
                txfPlayerTurn.setVisible(false);
                btnStart.setVisible(false);
                lblTurn.setVisible(false);
                txfDiceResult.setVisible(false);
            }
            case 1 -> {
                //After number of players is selected
                btnMinusNumOfPlayers.setVisible(false);
                btnPlusNumOfPlayers.setVisible(false);
                btnSelectNumOfPlayers.setVisible(false);
                lblAmmountOfPlayers.setVisible(false);
                txfNumOfPlayers.setVisible(false);
                for (int i = 0; i < numOfPlayers; i++) {
                    btnEditsArray[i].setVisible(true);
                    playerNamesArray[i].setVisible(true);
                }
            }
            case 2 -> {
                //Edit a player
                for (JButton jb : btnTokensArray)
                    jb.setVisible(true);
            }
            case 3 -> {
                //Finish editing a player
                for (JButton jb : btnTokensArray)
                    jb.setVisible(false);
            }
            case 4 -> {
                //Start game
                btnDice.setVisible(true);
                txfPlayerTurn.setVisible(true);
                lblTurn.setVisible(true);
                txfDiceResult.setVisible(true);
            }
            default -> {
            }
        }
    }
    
    public void buyPrompt() {
        System.out.println("can buy");
    }
    
    public void declareBankrupt(String playerName) {
        System.out.println(playerName + " is bankrupt");
    }
    
    private void selectPlayerToEdit(int playerNum) {
        currentPlayerToEdit = btnPlayersArray[playerNum-1];
        toggleComponents(2);
    }
    
    private void showPlayerData(int playerNum) {
        String playerString = Util.getUtil().getPlayers().getPlayerString(playerNum);
        JOptionPane.showMessageDialog(this, playerString,"Detalles de Jugador", JOptionPane.INFORMATION_MESSAGE);
    } 
    
    private void CommunnityChestMassage (){
        
        String playerString = Util.getUtil().getBank().getCommuinityChest().RandomCC(Util.getUtil().getPlayers().getPlayerTurn());
        CommunityChestButton.setContentAreaFilled(false);
        
        JOptionPane.showMessageDialog(this,"" + playerString );
    }
    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Board.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Board().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChanceButton;
    private javax.swing.JButton CommunityChestButton;
    private javax.swing.JButton btnDice;
    private javax.swing.JButton btnEditPlayer1;
    private javax.swing.JButton btnEditPlayer2;
    private javax.swing.JButton btnEditPlayer3;
    private javax.swing.JButton btnEditPlayer4;
    private javax.swing.JButton btnEditPlayer5;
    private javax.swing.JButton btnEditPlayer6;
    private javax.swing.JButton btnMinusNumOfPlayers;
    private javax.swing.JButton btnP1;
    private javax.swing.JButton btnP2;
    private javax.swing.JButton btnP3;
    private javax.swing.JButton btnP4;
    private javax.swing.JButton btnP5;
    private javax.swing.JButton btnP6;
    private javax.swing.JButton btnPlusNumOfPlayers;
    private javax.swing.JButton btnSelectNumOfPlayers;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnToken1;
    private javax.swing.JButton btnToken10;
    private javax.swing.JButton btnToken11;
    private javax.swing.JButton btnToken12;
    private javax.swing.JButton btnToken13;
    private javax.swing.JButton btnToken14;
    private javax.swing.JButton btnToken2;
    private javax.swing.JButton btnToken3;
    private javax.swing.JButton btnToken4;
    private javax.swing.JButton btnToken5;
    private javax.swing.JButton btnToken6;
    private javax.swing.JButton btnToken7;
    private javax.swing.JButton btnToken8;
    private javax.swing.JButton btnToken9;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAmmountOfPlayers;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTurn;
    private javax.swing.JPanel pnlStartGameOptions;
    private javax.swing.JTextField txfDiceResult;
    private javax.swing.JTextField txfEditPlayer1;
    private javax.swing.JTextField txfEditPlayer2;
    private javax.swing.JTextField txfEditPlayer3;
    private javax.swing.JTextField txfEditPlayer4;
    private javax.swing.JTextField txfEditPlayer5;
    private javax.swing.JTextField txfEditPlayer6;
    private javax.swing.JTextField txfNumOfPlayers;
    private javax.swing.JTextField txfPlayerTurn;
    // End of variables declaration//GEN-END:variables
}